# 1. Registration
# POST
# /api/auth/registration/
POST http://127.0.0.1:8000/api/auth/registration/
Content-Type: application/json

{
    "email": "djrestauth6@gmail.com",
    "first_name": "Rest",
    "last_name": "Auth",
    "password1": "mylogin8#",
    "password2": "mylogin8#"
}


# 2. Activation
# POST
# /api/auth/registration/verify-email/
POST http://127.0.0.1:8000/api/auth/registration/verify-email/
Content-Type: application/json

{
    "key": "NA:1s8x5Q:bjcvhGHU2OlsZ7K1yom6S-0vswhqcsPQnGh8gNAUkdk"
}


3. **Registration Email Resend(Incase you lost the firt activation email**
    ```http
    POST http://127.0.0.1:8000/api/auth/registration/resend-email/
    Content-Type: application/json

    {
        "email": "djrestauthy@gmail.com"
    }
    ```

4. **Account Confirmation Email**
    ```http
    POST http://127.0.0.1:8000/api/auth/account-confirm-email/
    Content-Type: application/json

    {
        "key": "Mg:1s8xvW:mHOdnhUAFaMG5-5NZAKe5c_ROBPiw-UqJT7uc1X_DEM"
    }
    ```

### Token-Based Authentication

5. **Login (Token-Based)**
    ```http
    POST http://127.0.0.1:8000/api/auth/login/
    Content-Type: application/json

    {
        "email": "djrestauth@gmail.com",
        "password": "mylogin8#"
    }
    ```

6. **Access Protected Endpoint Using Token**
    ```http
    GET http://127.0.0.1:8000/api/auth/profile/
    Authorization: Token ed5d5479e458869f73f5b7d5620f018f828816b8
    ```

7. **Logout (Token-Based)**
    ```http
    POST http://127.0.0.1:8000/api/auth/logout/
    Content-Type: application/json

    {
        "token": "ed5d5479e458869f73f5b7d5620f018f828816b8"
    }
    ```

### JWT-Based Authentication

8. **Login (JWT)**
    ```http
    POST http://127.0.0.1:8000/api/auth/login/
    Content-Type: application/json

    {
        "email": "djrestauth@gmail.com",
        "password": "mylogin8#"
    }
    ```

9. **Verify JWT**
    ```http
    POST http://127.0.0.1:8000/api/auth/token/verify/
    Content-Type: application/json

    {
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzOTY4Mjg5LCJpYXQiOjE3MTYxOTIyODksImp0aSI6IjM4N2I2YjYwZjBiMzRiNjQ5MzRkOWIwYTQ0YmYxNGRmIiwidXNlcl9pZCI6MTd9.xnFn-fPOM8BejYaEcKABGroaJfm4zwyubZif53steXI"
    }
    ```

9. **Refresh JWT**
    ```http
    POST http://127.0.0.1:8000/api/auth/token/refresh/
    Content-Type: application/json

    {
        "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMTc0NDI4OSwiaWF0IjoxNzE2MTkyMjg5LCJqdGkiOiIzNDJkZmMzM2FhYzY0NmQ5YWFkZjFlYzBjNTc1OGYwNSIsInVzZXJfaWQiOjE3fQ.BBhkmKUmiJ7vdqiVaMuckofUlVobIwMILL-_e94CEvk"
    }
    ```

10. **Access Protected Endpoint Using JWT**
    ```http
    GET http://127.0.0.1:8000/api/auth/profile/
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzOTY4Mzg3LCJpYXQiOjE3MTYxOTIyODksImp0aSI6ImRkYzExMjFlZjkxZDQ1MjQ5MDFlY2ExOGI2NjY1MDI5IiwidXNlcl9pZCI6MTd9.CCelN8nfa3pbLn5RSKYVA8EwmS7ZJYz0B2GGjY8arx8
    ```

### Additional Endpoints
11. **Password Change**
    ```http
    POST http://127.0.0.1:8000/api/auth/password/change/
    Content-Type: application/json
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzOTY4Mzg3LCJpYXQiOjE3MTYxOTIyODksImp0aSI6ImRkYzExMjFlZjkxZDQ1MjQ5MDFlY2ExOGI2NjY1MDI5IiwidXNlcl9pZCI6MTd9.CCelN8nfa3pbLn5RSKYVA8EwmS7ZJYz0B2GGjY8arx8

    {
        "old_password": "mylogin8#",
        "new_password1": "newpassword8#",
        "new_password2": "newpassword8#"
    }
    ```


12. **Password Reset**
    ```http
    POST http://127.0.0.1:8000/api/auth/password/reset/
    Content-Type: application/json

    {
        "email": "djrestauth@gmail.com"
    }
    ```

13. **Password Reset Confirm**
    ```http
    POST http://127.0.0.1:8000/api/auth/password/reset/confirm/
    Content-Type: application/json

    {
        "uid": "h",
        "token": "c7bg4t-942cfd4719eb71d423d4326054ba64bf",
        "new_password1": "mylogin8#",
        "new_password2": "mylogin8#"
    }
    ```

14. **Profile (GET)**
    ```http
    GET http://127.0.0.1:8000/api/auth/profile/
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzOTY4Mjg5LCJpYXQiOjE3MTYxOTIyODksImp0aSI6IjM4N2I2YjYwZjBiMzRiNjQ5MzRkOWIwYTQ0YmYxNGRmIiwidXNlcl9pZCI6MTd9.xnFn-fPOM8BejYaEcKABGroaJfm4zwyubZif53steXI
    ```

15. **Profile (PUT)**
    ```http
    PUT http://127.0.0.1:8000/api/auth/profile/
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzOTY4Mjg5LCJpYXQiOjE3MTYxOTIyODksImp0aSI6IjM4N2I2YjYwZjBiMzRiNjQ5MzRkOWIwYTQ0YmYxNGRmIiwidXNlcl9pZCI6MTd9.xnFn-fPOM8BejYaEcKABGroaJfm4zwyubZif53steXI
    Content-Type: application/json

    {
        "bio": "I am a software developer"
    }
    ```

16. **Profile (PATCH)**
    ```http
    PATCH http://127.0.0.1:8000/api/auth/profile/
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzOTY4Mjg5LCJpYXQiOjE3MTYxOTIyODksImp0aSI6IjM4N2I2YjYwZjBiMzRiNjQ5MzRkOWIwYTQ0YmYxNGRmIiwidXNlcl9pZCI6MTd9.xnFn-fPOM8BejYaEcKABGroaJfm4zwyubZif53steXI
    Content-Type: application/json

    {
        "bio": "I am a software developer"
    }
    ```

17. **User (GET)**
    ```http
    GET http://127.0.0.1:8000/api/auth/user/
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzOTY4Mjg5LCJpYXQiOjE3MTYxOTIyODksImp0aSI6IjM4N2I2YjYwZjBiMzRiNjQ5MzRkOWIwYTQ0YmYxNGRmIiwidXNlcl9pZCI6MTd9.xnFn-fPOM8BejYaEcKABGroaJfm4zwyubZif53steXI
    ```

16. **User (PUT)**
    ```http
    PUT http://127.0.0.1:8000/api/auth/user/
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzOTY4Mjg5LCJpYXQiOjE3MTYxOTIyODksImp0aSI6IjM4N2I2YjYwZjBiMzRiNjQ5MzRkOWIwYTQ0YmYxNGRmIiwidXNlcl9pZCI6MTd9.xnFn-fPOM8BejYaEcKABGroaJfm4zwyubZif53steXI
    Content-Type: application/json

    {
        "first_name": "RestUpdated",
        "last_name": "AuthUpdated",
        "email": "djrestauth@gmail.com"
    }
    ```

17. **User (PATCH)**
    ```http
    PATCH http://127.0.0.1:8000/api/auth/user/
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzOTY4Mjg5LCJpYXQiOjE3MTYxOTIyODksImp0aSI6IjM4N2I2YjYwZjBiMzRiNjQ5MzRkOWIwYTQ0YmYxNGRmIiwidXNlcl9pZCI6MTd9.xnFn-fPOM8BejYaEcKABGroaJfm4zwyubZif53steXI
    Content-Type: application/json

    {
        "first_name": "RestUpdated"
    }
    ```

18. **Social Auth**
    ```http
    POST http://127.0.0.1:8000/api/auth/google/
    Content-Type: application/json

    {
        "code": "4/0AdLIrYcjYMq3ezOFk9zdI53rQITe83KUAu7PmlwH0lR9H9_iAothjfm4OURRTCt-z6MHfw"
    }
    ```

